version: "3"

services:
  frps:
    image: registry.cn-chengdu.aliyuncs.com/1s/frp
    volumes:
      - "./frpc.ini:/opt/frp/frpc.ini"
      - "./logs:/opt/frp/logs"
    container_name: frpc
    restart: always
    environment:
      - entrypoint=./frpc -c frpc.ini